[versions]
adventure-api = "4.18.0"
adventure-platforms = "4.3.4"
brigadier = "1.0.18"
curseforge-gradle = "1.1.15"
# see https://fabricmc.net/develop/ for new versions
fabric-loom = "1.14-SNAPSHOT"
forge-gradle = "[6.0.46,7)"
gson = "2.12.1"
hangar = "0.1.3"
jetbrains-annotations = "26.0.2"
mclogs = { strictly = "[6.1,7.0)", prefer = "6.1.0" }
minotaur = "2.8.7"
# see https://projects.neoforged.net/neoforged/moddevgradle for new versions
neoforge-moddev = "2.0.111"
night-config = { strictly = "[3.7,4.0)", prefer = "3.8.1" }
runtask = "2.3.1"
shadow = "9.0.0-rc1"
slf4j = "2.0.16"
velocity-api = "3.4.0-SNAPSHOT"

[libraries]
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-bukkit = { module = "net.kyori:adventure-platform-bukkit", version.ref = "adventure-platforms" }
adventure-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-platforms" }
brigadier = { module = "com.mojang:brigadier", version.ref = "brigadier" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
mclogs-api = { module = "gs.mclo:api", version.ref = "mclogs" }
nightconfig-core = { module = "com.electronwill.night-config:core", version.ref = "night-config" }
nightconfig-toml = { module = "com.electronwill.night-config:toml", version.ref = "night-config" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity-api" }

[plugins]
curseforge-gradle = { id = "net.darkhax.curseforgegradle", version.ref = "curseforge-gradle" }
fabric-loom = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
forge-gradle = { id = "net.minecraftforge.gradle", version.ref = "forge-gradle" }
hangar = { id = "io.papermc.hangar-publish-plugin", version.ref = "hangar" }
minotaur = { id = "com.modrinth.minotaur", version.ref = "minotaur" }
neoforge-moddev = { id = "net.neoforged.moddev", version.ref = "neoforge-moddev" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
run-paper = { id = "xyz.jpenilla.run-paper", version.ref = "runtask" }
run-velocity = { id = "xyz.jpenilla.run-velocity", version.ref = "runtask" }
